### PR TITLE
adds monger

### PR DESCRIPTION
**Pull request by alekcz**
Unfortunately this one didn't work. SSL issues that I couldn't bypass.

### CODE REVIEW

**Comment by BrunoBonacci** [comment]
Hi,
nice work, thanks!!!
did you try adding `--enable-https` to the `native-image` options to handle the **https**?

**Comment by alekcz** [comment]
I thought that `--enable-https` and `--enable-url-protocols=http,https` were equivalent. Lemme give it a shot.

**Comment by alekcz** [comment]
The issue seems to be that `sun.security.provider.NativePRNG` is on the heap when it shouldn't be and it looks like it's coming from within the mongodb driver

**Comment by BrunoBonacci** [comment]
;-( 

thanks for trying this up

**Pull request merged**
